// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcBhadXL054o2LiC0ISlW_kyYjkApGTYI',
    appId: '1:649624206193:android:247f46c9ddb5f10bc3d4d0',
    messagingSenderId: '649624206193',
    projectId: 'flutter-b4',
    storageBucket: 'flutter-b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8y8tl9iYHWFv6AQ7dm1dcXLUxUBehvRE',
    appId: '1:649624206193:ios:c71e6d048efd54b0c3d4d0',
    messagingSenderId: '649624206193',
    projectId: 'flutter-b4',
    storageBucket: 'flutter-b4.appspot.com',
    androidClientId: '649624206193-qnjstbaal8295jpnjjt9outorivh4fvg.apps.googleusercontent.com',
    iosClientId: '649624206193-a5pg8omakfu3pbefq40hu426d5qpj6ng.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterB9',
  );
}
